# Generated by Django 3.2.7 on 2021-09-07 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='button_tex',
            new_name='button_text',
        ),
    ]
