# Generated by Django 3.2.7 on 2021-09-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_rename_button_tex_slider_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
