# Generated by Django 3.2.7 on 2021-09-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_auto_20210908_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='youtube_link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
